#!/bin/sh
#
# Updates a file that has been generated by genopts and adds fields
#
set -e

file=$1
if [[ -z "$file" ]]; then
    echo "file required"
    exit 1
fi
shift

cmdline=$(grep "// genopts" "$file" | sed "s#// genopts ##")
cmdline+=" $@"
# $(dirname $0)/genopts.sh "$cmdline"
~/go/bin/genopts $cmdline