#!/bin/sh
#
# Updates a file that has been generated by genopts and adds fields
#
set -e

file=$1
if [[ -z "$file" ]]; then
    echo "file required"
    exit 1
fi
shift

cmdline=$(grep "// genopts" "$file" | sed "s#// genopts ##" | sed "s#'##g")
cmdline+=" $@"
~/go/bin/genopts $cmdline